workspace:
  base: /go
  path: src/github.com/drone/drone-yaml

pipeline:
  deps:
    image: golang:1.9
    commands:
      - go get -u github.com/golang/dep/cmd/dep
      - dep ensure
  test:
    image: golang:1.9
    commands:
      - go test -v --cover ./...
