# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"

# https://github.com/golang/dep/issues/944
# [prune]
#   non-go = true
#   test-go = true
#   unused-packages = true


[[constraint]]
  name = "github.com/alecthomas/kingpin"
  version = "2.2.6"

[[constraint]]
  name = "github.com/bmatcuk/doublestar"
  version = "1.0.9"

[[constraint]]
  name = "github.com/coreos/go-semver"
  version = "0.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/dchest/uniuri"

[[constraint]]
  name = "github.com/docker/distribution"
  # version = "2.6.2"
  # branch = "master"
  revision = "749f6afb4572201e3c37325d0ffedb6f32be8950"

[[constraint]]
  name = "github.com/docker/go-units"
  version = "0.3.3"

[[constraint]]
  branch = "master"
  name = "github.com/drone/drone-runtime"

[[constraint]]
  branch = "master"
  name = "github.com/flynn/go-shlex"

[[constraint]]
  name = "github.com/ghodss/yaml"
  version = "1.0.0"

[[constraint]]
  name = "github.com/gosimple/slug"
  version = "1.1.1"

[[constraint]]
  name = "github.com/kr/pretty"
  version = "0.1.0"

[[constraint]]
  name = "github.com/mattn/go-isatty"
  version = "0.0.3"

[[constraint]]
  branch = "master"
  name = "github.com/vincent-petithory/dataurl"

[[constraint]]
  branch = "fix-for-issue-91"
  name = "gopkg.in/yaml.v2"
  source = "https://github.com/vinzenz/yaml.git"

[prune]
  go-tests = true
  unused-packages = true
