#!/bin/sh

drone-yaml-v1 --trusted samples/1_simple.yml   > samples/1_simple.json
drone-yaml-v1 --trusted samples/2_network.yml  > samples/2_network.json
drone-yaml-v1 --trusted samples/3_volumes.yml  > samples/3_volumes.json
drone-yaml-v1 --trusted samples/4_services.yml > samples/4_services.json
drone-yaml-v1 --trusted samples/5_parallel.yml > samples/5_parallel.json

drone-yaml-v1 --registry=https://octocat:12345@docker.io samples/7_registry.yml > samples/7_registry.json
drone-yaml-v1 --secret=SSH_USERNAME=root --secret=SSH_PASSWORD=12345 samples/8_secrets.yml > samples/8_secrets.json
drone-yaml-v1 --netrc-login=octocat --netrc-password=12345 --netrc-machine=github.com samples/9_netrc.yml > samples/9_netrc.json


drone-yaml-v1 --trusted samples/10_plugin.yml > samples/10_plugin.json
drone-yaml-v1 --mem-limit=2GB --mem-swap-limit=4GB samples/11_limits.yml > samples/11_limits.json

drone-yaml-v1 --trusted samples/12_workspace.yml > samples/12_workspace.json
drone-yaml-v1 --trusted samples/13_data_volume.yml > samples/13_data_volume.json


drone-yaml-v1 \
  --clone \
  --env=DRONE_REF=refs/heads/master \
  --env=DRONE_EVENT=push \
  --env=DRONE_COMMIT_SHA=c0e474cb2b076afba767d6cff9ec8d0949f5518a \
  --env=DRONE_BRANCH=master \
  --env=DRONE_REF=refs/head/master \
  --env=DRONE_REMOTE_URL=https://github.com/drone/expr.git \
  samples/14_clone.yml > samples/14_clone.json
