#!/bin/sh

drone-yaml-v1 --trusted samples/windows/1_simple.yml   > samples/windows/1_simple.json

drone-yaml-v1 \
  --clone \
  --env=DRONE_REF=refs/heads/master \
  --env=DRONE_EVENT=push \
  --env=DRONE_COMMIT_SHA=c0e474cb2b076afba767d6cff9ec8d0949f5518a \
  --env=DRONE_BRANCH=master \
  --env=DRONE_REF=refs/head/master \
  --env=DRONE_REMOTE_URL=https://github.com/drone/expr.git \
  samples/windows/2_clone.yml > samples/windows/2_clone.json
